- build_utils/postcss-build.js
- package.json
- src/components/app/style-module.html
- yarn.lock
> Ref #27 - Add CSSNext and remove autoprefixer (included in cssnext)

- webpack.config.js
> Add svgs and pngs to serviceworker

- webpack.config.js
Let Service-Worker cache fonts, too
> Extend WorkboxJS for Fonts

- src/index.html
- webpack.config.js
> Re-added webcomponents-loader.js with correct logic

- package.json
- src/manifest.json
- webpack-module.config.js
- webpack-nomodule.config.js
- webpack.config.js
- yarn.lock
> feat(split-webpack): splitting webpack configuration

- package.json
- webpack.config.js
> fix(env vars): a better way to pass env vars to webpack

- webpack-module.config.js
- webpack-nomodule.config.js
- webpack.config.js
> Fixing env vars check

- README.md
- package.json
- webpack-module.config.js
- webpack-nomodule.config.js
- webpack.config.js
- yarn.lock
> Added object-spread babel pluign

- webpack.config.js
This is actually way better, and it's working as expected.
> Workbox Service Worker generation fix

- postcss.config.js
> refactor(postcss-config): refactoring with require()

- package.json
- src/components/containers/sk-app/index.js
- src/components/dumbs/sk-button/index.js
- yarn.lock
> feat(polymer3-pre12): updated Polymer to new pre

- package.json
- scripts/postinstall.js
> fix(windows-postinstall): fixed postinstall script for Windows

- README.md
- package.json
- scripts/postinstall.js
- src/components/containers/sk-app/index.js
- src/components/containers/sk-app/template.html
- src/components/dumbs/sk-button/index.js
- src/index.html
- yarn.lock
> Develop to Master for v1.0.0-beta-4

- src/index.html
- src/manifest.json
> fix(manifest-meta): fixed meta for manifest.json and others

- README.md
Add the depth for fast clone
> IMPORTANT NOTE: Make sure to select the `develop` branch before sending the pull request.
> For reduce time in the clone

- postcss.config.js
- webpack.config.js
> feat: switch to a better browserslist

- package.json
- webpack.config.js
- yarn.lock
> fix(webcomponents-v2): fixed downloaded versions and bundles

- package.json
> chore(package): update cssnano to version 4.0.5

- package.json
> chore(package): update autoprefixer to version 9.1.2

- package.json
- yarn.lock
> IMPORTANT NOTE: Make sure to select the `develop` branch before sending the pull request.
> Greenkeeper/webpack 4.19.0

- package.json
> chore(package): update autoprefixer to version 9.4.2

- package.json
> chore(package): update webpack to version 4.27.0
